"use strict";;(function($){'use strict';var WPPopups={popups:{},byBind:{'class':[],'href':[]},init:function init(){$(document).ready(WPPopups.ready);$(window).on('load',WPPopups.load);$(document).on('wppopupsReady',WPPopups.start);WPPopups.bindUIActions();},ready:function ready(){$(document).trigger('wppopupsBeforeReady');if($(".spu-box").length==0)return false;var data={action:'wppopups_rules',pid:wppopups_vars.pid,referrer:document.referrer,url:document.documentURI,query_string:document.location.search,is_category:wppopups_vars.is_category,is_archive:wppopups_vars.is_archive,is_singular:wppopups_vars.is_singular,is_preview:wppopups_vars.is_preview,is_search:wppopups_vars.is_search,is_front_page:wppopups_vars.is_front_page,is_blog_page:wppopups_vars.is_blog_page,popups:[]};$(".spu-box").each(function(){var $popup=$(this),$id=$popup.data('id'),$rules=WPPopups.settings($popup,'rules');if($id){data.popups.push({id:$id,rules:JSON.stringify($rules),parent:$popup.data('parent')});}});var ajax={url:wppopups_vars.ajax_url,data:window.wp.hooks.applyFilters('wppopups_pre_ready_data',data),cache:false,type:'POST',dataType:'json',timeout:30000,success:function success(r){if(r.success){r.success.forEach(function(id){WPPopups.removePopup(id);});}
$(document).trigger('wppopupsReady');},error:function error(r){console.log(r);}};$.ajax(ajax);},load:function load(){$(".spu-box").each(function(){var $popup=$(this);WPPopups.centerPopup($popup,true);});},start:function start(){WPPopups.initVideoSources();WPPopups.resetPopupsContent();WPPopups.hashTriggerPopups();WPPopups.loopPopups();WPPopups.initSocialShortcodes();$(document).trigger('wppopupsStarted');},loopPopups:function loopPopups(){$(".spu-box").each(function(){var $popup=$(this),$id=$popup.data('id');WPPopups.popups[$id]=$popup;WPPopups.bindPopupTriggers($popup);WPPopups.bindClickTriggers($popup);WPPopups.formSubmissions($popup);$(window).resize(function(){WPPopups.checkPopupSize($popup);WPPopups.centerPopup($popup,true);});window.wp.hooks.doAction('wppopups_loop',$popup);window.wp.hooks.addAction('wppopups_show_popup','wppopups',WPPopups.centerPopup,99);$popup.hide();});},triggerBySeconds:function triggerBySeconds(value,$popup){if(value===''){return;}
if($popup.timer){clearTimeout($popup.timer);}
$popup.timer=window.setTimeout(function(){if(WPPopups.checkConvertion($popup)){WPPopups.showPopup($popup);}},parseInt(value,10)*1000);},triggerByPercentage:function triggerByPercentage(value,$popup){if(value===''){return;}
var $settings=WPPopups.settings($popup,'settings');$(window).on('scroll.per'+$popup.data('id'),function(){if($popup.timer){clearTimeout($popup.timer);}
$popup.timer=window.setTimeout(function(){var triggerHeight=parseInt(value,10)/100*$(document).height();var scrollY=$(window).scrollTop(),trigger=scrollY+$(window).height()>=triggerHeight;if(trigger&&WPPopups.checkConvertion($popup)){if(!$settings.auto_hide){$(window).off('scroll.per'+$popup.data('id'));}
WPPopups.showPopup($popup);}else{WPPopups.hidePopup($popup,false,10,false);}},100);});},triggerByPixels:function triggerByPixels(value,$popup){if(value===''){return;}
var $settings=WPPopups.settings($popup,'settings');$(window).on('scroll.pix'+$popup.data('id'),function(){if($popup.timer){clearTimeout($popup.timer);}
$popup.timer=window.setTimeout(function(){var scrollY=$(window).scrollTop(),trigger=scrollY>=parseInt(value,10);if(trigger&&WPPopups.checkConvertion($popup)){if(!$settings.auto_hide){$(window).off('scroll.pix'+$popup.data('id'));}
WPPopups.showPopup($popup);}else{WPPopups.hidePopup($popup,false,10,false);}},100);});},triggerByClass:function triggerByClass(value,$popup){if(value===''){return;}
value=value.charAt(0)!='.'?'.'+value:value;WPPopups.setBindActions(value,'class');$(document.body).on('click',value,function(e){e.preventDefault();WPPopups.showPopup($popup,true);});},bindClickTriggers:function bindClickTriggers($popup){var id=$popup.data('id');WPPopups.setBindActions('.spu-open-'+id,'class');WPPopups.setBindActions('#spu-'+id,'href');$(document.body).on('click','a[href="#spu-'+id+'"], .spu-open-'+id,function(e){e.preventDefault();WPPopups.showPopup($popup,true);});$('a[href="#spu-'+id+'"], .spu-open-'+id).css('cursor','pointer').addClass('spu-clickable');},bindPopupTriggers:function bindPopupTriggers($popup){if(window.wp.hooks.applyFilters('wppopups_disable_triggers',false,$popup))return;var $triggers=WPPopups.settings($popup,'triggers');if(Object.keys($triggers).length){for(var i in $triggers){var func='triggerBy'+$triggers[i].trigger.charAt(0).toUpperCase()+$triggers[i].trigger.substr(1),settings=WPPopups.settings($popup,'settings');if(!WPPopups.hasCookies($popup)||wppopups_vars.is_preview||func=='triggerByClass'||wppopups_vars.is_admin&&settings.test_mode=='1'){if(typeof WPPopups[func]=='function'){WPPopups[func]($triggers[i].value,$popup);}
window.wp.hooks.doAction('wppopups_trigger_popup',func,$triggers[i].value,$popup);}}}},bindUIActions:function bindUIActions(){$(document).on('click','.spu-box a:not(".spu-close-popup, .spu-box .flp_wrapper a, .spu-box .spu-not-close, .spu-box .spu-not-close a, .spu-box .spu-gdpr a")',function(){WPPopups.hidePopup($(this),true);});$(document).on('click','.spu-box .spu-close-convert,.spu-box .spu-close-convert a',function(e){e.preventDefault();WPPopups.hidePopup($(this),true);});$(document).on('click','.spu-box .spu-close-popup',function(e){WPPopups.hidePopup($(this),false);});$(document).keyup(function(e){if(e.keyCode==27){WPPopups.togglePopups(false,false);}});var ua=navigator.userAgent,event=ua.match(/iPad/i)||ua.match(/iPhone/i)?"touchstart":"click";$('body').on(event,function(ev){var $target=$(ev.target);if($target.is('input.nf-element'))return;if(WPPopups.checkBindActions($target))return;if(window.wp.hooks.applyFilters('wppopups_disable_click_out',false,$target))return;if(ev.originalEvent!==undefined&&!$target.is('.spu-box *, .spu-box')){WPPopups.togglePopups(false,false);}});},settings:function settings(popup,key){var settings={};if(popup.data('settings')){settings=popup.data('settings');}
if(key&&typeof settings[key]!='undefined'){return settings[key];}
return settings;},togglePopups:function togglePopups(show,conversion){$('.spu-box').each(function(){if(show){WPPopups.showPopup($(this));}else{if(window.wp.hooks.applyFilters('wppopups_allow_togglePopups',true,$(this))){WPPopups.hidePopup($(this),conversion);}}});},showPopup:function showPopup(popup){var force=arguments.length>1&&arguments[1]!==undefined?arguments[1]:false;var $popup=WPPopups.getPopup(popup),$id=$popup.data('id'),$bg=$('#spu-bg-'+$id);if($popup.is(":animated")||$popup.is(":visible")){return false;}
if(!force&&WPPopups.hasCookies($popup)){return false;}
$popup.parent('.wppopups-whole').show();WPPopups.toggleBlur($popup,true);WPPopups.centerPopup($popup);WPPopups.checkPopupSize($popup);var animation=WPPopups.settings($popup,'animation');switch(animation.animation){case 'fade':$popup.hide().fadeIn('slow');break;case 'slide':$popup.hide().slideDown('slow');break;default:$popup.show();break;}
if(!$popup.hasClass('spu-position-top-bar')&&!$popup.hasClass('spu-position-bottom-bar')){if(animation.animation==='disable'){$bg.show();}else{$bg.fadeIn();}}
window.wp.hooks.doAction('wppopups_show_popup',$popup);WPPopups.toggleVideoSources($popup,true);$popup.trigger('wppopups.popup_opened',[$id]);},hidePopup:function hidePopup(popup,conversion){var time=arguments.length>2&&arguments[2]!==undefined?arguments[2]:0;var cookie=arguments.length>3&&arguments[3]!==undefined?arguments[3]:true;var $popup=WPPopups.getPopup(popup),$id=$popup.data('id'),$bg=$('#spu-bg-'+$id);if($popup.is(":animated")||$popup.is(":hidden")||window.wp.hooks.applyFilters('wppopups_cancel_hide',false,$popup,conversion)){return false;}
if(conversion===true){WPPopups.popupConverted($popup,cookie);}
var settings=WPPopups.settings($popup,'settings');if(settings.close_on_conversion=='1'&&conversion||!conversion){setTimeout(function(){var animation=WPPopups.settings($popup,'animation');switch(animation.animation){case 'slide':$popup.slideUp('slow');$bg.fadeOut();break;case 'disable':$popup.hide();$bg.hide();break;default:$popup.removeClass('spu-animation-animated');$popup.fadeOut('slow');$bg.fadeOut();break;}
window.wp.hooks.doAction('wppopups_hide_popup',$popup);WPPopups.toggleVideoSources($popup,false);},parseInt(time,10));}
WPPopups.toggleBlur($popup,false);WPPopups.popupClosed($popup,cookie);},centerPopup:function centerPopup(popup,animate){if(!popup.hasClass('spu-position-centered')&&!popup.hasClass('spu-position-float-right')&&!popup.hasClass('spu-position-float-left')){return;}
if(popup.is(':animated')){return;}
var ww=$(window).width(),wh=$(window).height(),pw=popup.outerWidth(),ph=popup.outerHeight();var boxLeft=ww/2-pw/2,boxTop=wh/2-ph/2;var css={top:boxTop};if(popup.hasClass('spu-position-centered')){css.left=boxLeft;}
if(animate){popup.animate(css,{queue:!1,duration:200});}else{popup.css(css);}},removePopup:function removePopup(popup){var $popup=WPPopups.getPopup(popup),$id=$popup.data('id'),$bg=$('#spu-bg-'+$id),$css=$('#spu-css-'+$id);$popup.remove();$bg.remove();$css.remove();},popupConverted:function popupConverted($popup){var cookie=arguments.length>1&&arguments[1]!==undefined?arguments[1]:true;if(cookie){var settings=WPPopups.settings($popup,'settings'),duration=parseFloat(settings.conversion_cookie_duration),_cookie=settings.conversion_cookie_name,type=settings.conversion_cookie_type;if(duration>0){WPPopups.createCookie(_cookie,true,duration,type);}}
$popup.trigger('wppopups.popup_converted',[$popup.data('id')]);},popupClosed:function popupClosed($popup){var cookie=arguments.length>1&&arguments[1]!==undefined?arguments[1]:true;if(cookie){var settings=WPPopups.settings($popup,'settings'),duration=parseFloat(settings.closing_cookie_duration),_cookie2=settings.closing_cookie_name,type=settings.closing_cookie_type;if(duration>0){WPPopups.createCookie(_cookie2,true,duration,type);}}
$popup.trigger('wppopups.popup_closed',[$popup.data('id')]);},hasCookies:function hasCookies($popup){var $settings=WPPopups.settings($popup,'settings'),conversion_name=$settings.conversion_cookie_name,closing_name=$settings.closing_cookie_name;var hasCookies=false;if(!(wppopups_vars.is_admin&&$settings.test_mode=='1')&&(WPPopups.getCookie(conversion_name)||WPPopups.getCookie(closing_name))){hasCookies=true;}
return hasCookies;},toggleBlur:function toggleBlur($popup,show){var colors=WPPopups.settings($popup,'colors'),$id=$popup.data('id'),$box_css=$('#spu-css-'+$id);if(colors.show_overlay=='yes-blur'){if(show){var blur_px=colors.overlay_blur?colors.overlay_blur:2,blur_css='/* ini:blur */body > *:not(.wppopups-whole) { -webkit-filter: blur('+blur_px+'px); -moz-filter: blur('+blur_px+'px); -o-filter: blur('+blur_px+'px); -ms-filter: blur('+blur_px+'px); filter: blur('+blur_px+'px); }/* fin:blur */';$box_css.append(blur_css);}else{var css=$box_css.text(),ini=css.indexOf('/* ini:blur */'),pro=css.substring(ini);$box_css.text(css.replace(pro,''));}}},initVideoSources:function initVideoSources(){var iframe=$('.spu-box iframe');if(iframe&&iframe.length){iframe.each(function(){$(this).attr('spusrc',$(this).attr('src'));$(this).attr('src','https://#');});}},toggleVideoSources:function toggleVideoSources(popup,show){var iframe=popup.find('iframe');if(iframe&&iframe.length){iframe.each(function(){if(show){if($(this).attr('spusrc')){$(this).attr('src',$(this).attr('spusrc'));}}else{$(this).attr('src','https://#');}});}},resetPopupsContent:function resetPopupsContent(){$(".spu-content").children().first().not('.spu-fields-container').css({"margin-top":0,"padding-top":0}).end().last().not('.spu-fields-container').css({'margin-bottom':0,'padding-bottom':0});},hashTriggerPopups:function hashTriggerPopups(){if(window.location.hash&&window.location.hash.length>0){var hash=window.location.hash,form_key=hash.substring(1).indexOf('spu-form'),link_key=hash.substring(1).indexOf('spu-open'),form_popup=form_key!==-1,link_popup=link_key!==-1;if(form_popup)var i=form_key+10;else if(link_popup)var i=link_key+10;if((link_popup||form_popup)&&$('#spu-'+hash.substring(i)).is('.spu-box')){var popup=$('#spu-'+hash.substring(i));if(form_popup&&popup.find('.spu-close-popup').length<2){popup.find('.spu-content').append('<p style="text-align: center"><button class="btn btn-primary spu-close-popup">Close</button></p>');}
if(form_popup){$(window).off('scroll.per'+popup.data('id'));$(window).off('scroll.pix'+popup.data('id'));WPPopups.popupConverted(popup);}
setTimeout(function(){WPPopups.showPopup(popup,true);},200);}}},formSubmissions:function formSubmissions($popup){var popup_id=$popup.data('id');$popup.find('form').each(function(){var box_form=$(this),action=box_form.attr('action')||'';box_form.attr('action',action+'#spu-form-'+popup_id);});$(document).on('nfFormSubmitResponse',function(){$popup.trigger('wppopups.form_submitted',[popup_id]);WPPopups.hidePopup($popup,true,2000);});$popup.on('wpcf7mailsent',function(){$popup.trigger('wppopups.form_submitted',[popup_id]);WPPopups.hidePopup($popup,true,2000);});$(document).on('gform_post_render',function(){$popup.trigger('wppopups.form_submitted',[popup_id]);WPPopups.hidePopup($popup,true,2000);});$(document).on('cf.submission',function(){$popup.trigger('wppopups.form_submitted',[popup_id]);WPPopups.hidePopup($popup,true,2000);});$(document).on('wpformsAjaxSubmitSuccess',function(){$popup.trigger('wppopups.form_submitted',[popup_id]);WPPopups.hidePopup($popup,true,2000);});},checkPopupSize:function checkPopupSize($popup){if($popup.outerHeight()+150>=$(window).height()){$popup.css('overflow','auto').addClass('spu-scrollable');$popup.css('max-height',$(window).height());}else{$popup.css('overflow','initial').removeClass('spu-scrollable');$popup.css('max-height','');}},initSocialShortcodes:function initSocialShortcodes(){if(wppopups_vars.facebook){var SPUfb=false,FbTimer=setInterval(function(){if(typeof FB!=='undefined'&&!SPUfb){try{FB.Event.subscribe('edge.create',function(href,html_element){var $popup=$(html_element).parents('.spu-box');if($popup.length){WPPopups.hidePopup($popup,true);}});}catch(ex){console.log(ex);}
SPUfb=true;clearInterval(FbTimer);}},1000);}
if(wppopups_vars.twitter){if(typeof twttr!=='undefined'){try{twttr.ready(function(twttr){twttr.events.bind('tweet',WPPopups.twitterCB);twttr.events.bind('follow',WPPopups.twitterCB);});}catch(ex){}}}
if(wppopups_vars.google){if(typeof twttr!=='undefined'){try{twttr.ready(function(twttr){twttr.events.bind('tweet',WPPopups.twitterCB);twttr.events.bind('follow',WPPopups.twitterCB);});}catch(ex){}}}},googleCB:function googleCB(a){if("on"==a.state){var box_id=$('.spu-gogl').data('box-id');if(box_id){WPPopups.hidePopup(box_id,true);}}},closeGoogle:function closeGoogle(a){if("confirm"==a.type){var box_id=$('.spu-gogl').data('box-id');if(box_id){WPPopups.hidePopup(box_id,true);}}},twitterCB:function twitterCB(intent_event){var $popup=$(intent_event.target).parents('.spu-box');if($popup){WPPopups.hidePopup($popup,true);}},setUserIndentifier:function setUserIndentifier(){if(wppopups_settings.uuid_cookie&&!WPPopups.getCookie('_wpfuuid')){var s=new Array(36),hexDigits='0123456789abcdef',uuid;for(var i=0;i<36;i++){s[i]=hexDigits.substr(Math.floor(Math.random()*0x10),1);}
s[14]="4";s[19]=hexDigits.substr(s[19]&0x3|0x8,1);s[8]=s[13]=s[18]=s[23]='-';uuid=s.join("");WPPopups.createCookie('_wpfuuid',uuid,3999);}},setBindActions:function setBindActions(){var bind_name=arguments.length>0&&arguments[0]!==undefined?arguments[0]:'';var bind_type=arguments.length>1&&arguments[1]!==undefined?arguments[1]:'class';if(bind_name!=''){switch(bind_type){case 'class':bind_name=bind_name.charAt(0)=='.'?bind_name.substring(1):bind_name;if($.inArray(bind_name,WPPopups.byBind['class'])===-1)WPPopups.byBind['class'].push(bind_name);break;case 'href':if($.inArray(bind_name,WPPopups.byBind['href'])===-1)WPPopups.byBind['href'].push(bind_name);break;}
window.wp.hooks.doAction('wppopups_set_bindactions',bind_name,bind_type);}},checkBindActions:function checkBindActions(target){var $classes=WPPopups.byBind['class'];for(var i in $classes){if(target.hasClass($classes[i])){return true;}}
var $href=WPPopups.byBind['href'];for(var _i in $href){if(target.attr('href')==$href[_i]){return true;}}
return false;},createCookie:function createCookie(name,value){var duration=arguments.length>2&&arguments[2]!==undefined?arguments[2]:999;var type=arguments.length>3&&arguments[3]!==undefined?arguments[3]:'d';var expires='';if(duration&&type){if('-1'===duration){expires='';}else{var cookie_time;switch(type){case 'm':cookie_time=60*1000;break;case 'h':cookie_time=60*60*1000;break;default:cookie_time=24*60*60*1000;}
var date=new Date();date.setTime(date.getTime()+parseInt(duration)*cookie_time);expires='; expires='+date.toGMTString();}}else{expires='; expires=Thu, 01 Jan 1970 00:00:01 GMT';}
document.cookie=name+'='+value+expires+'; path=/';},getCookie:function getCookie(name){var nameEQ=name+'=',ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===' '){c=c.substring(1,c.length);}
if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length);}}
return null;},removeCookie:function removeCookie(name){WPPopups.createCookie(name,'',-1);},isNumber:function isNumber(n){return!isNaN(parseFloat(n))&&!isNaN(n-0);},getPopup:function getPopup(popup){if(WPPopups.isNumber(popup)){return $('#spu-'+parseInt(popup));}
if(popup.is('.spu-box')){return popup;}
return popup.closest('.spu-box');},checkConvertion:function checkConvertion($popup){if(!$popup.hasClass('yes-convert')&&!$popup.hasClass('no-convert'))return true;var $settings=WPPopups.settings($('#spu-'+$popup.data('convert-id')),'settings');var popup_converted=false;if(WPPopups.getCookie($settings.conversion_cookie_name)){popup_converted=true;}
if($popup.hasClass('yes-convert')){return popup_converted;}else{return!popup_converted;}}};WPPopups.init();window.wppopups=WPPopups;})(jQuery);